<?php
/**
 * @file
 * Provides install, upgrade and un-install functions for ccl_blocks.
 */

/**
 * Implements hook_uninstall().
 *
 * Remove links created by this submodule.
 */
function ccl_local_actions_uninstall() {
  db_delete('ccl')
  ->condition('type', 'local_actions')
  ->execute();
}

// TODO The old hook_update_N functions cannot be applied to Backdrop.
function ccl_local_actions_update_7100() { }
